name: statsfl
description: A simple FPS monitor for Flutter
version: 0.0.2
author: shawn@gskinner.com
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
